version: '3.8'
services:
  keyvault:
    build:
      context: .
      dockerfile: ./apps/keyvault/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/apps/keyvault
      - /usr/src/apps/keyvault/node_modules
    container_name: keyvault
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  key-master-service:
    build:
      context: .
      dockerfile: ./apps/key-master-service/Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - .:/apps/key-master-service
      - /usr/src/apps/key-master-service/node_modules
    container_name: key-master-service
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  token-info-service:
    build:
      context: .
      dockerfile: ./apps/token-info-service/Dockerfile
    ports:
      - '3002:3002'
    volumes:
      - .:/apps/token-info-service
      - /usr/src/apps/token-info-service/node_modules
    container_name: token-info-service
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: keyvault-dev
      POSTGRES_PASSWORD: SuperCoolPassword123
      POSTGRES_DB: keyvault
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
