version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: keyvault-dev
      POSTGRES_PASSWORD: SuperCoolPassword123
      POSTGRES_DB: keyvault
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
